name: Build and Push

on:
  release:
    types: [published]

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: docker build
        run: docker build . --file Dockerfile --tag rickbassham/tesla-dashboard:latest
      - name: docker login
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
        run: echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
      - name: docker push
        run: |
          VERSION=$(echo "${{ github.ref }}" | sed -e 's,.*/\(.*\),\1,')
          docker tag rickbassham/tesla-dashboard:latest rickbassham/tesla-dashboard:$VERSION
          docker push rickbassham/tesla-dashboard:latest
          docker push rickbassham/tesla-dashboard:$VERSION
