name: Build and Push

on:
  release:
    types: [created]

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: docker build
        run: |
          VERSION=$(echo "${{ github.ref }}" | sed -e 's,.*/\(.*\),\1,')
          docker build . --file Dockerfile --tag rickbassham/tesla-dashboard:$VERSION
      - name: docker login
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
        run: echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
      - name: docker push
        run: |
          VERSION=$(echo "${{ github.ref }}" | sed -e 's,.*/\(.*\),\1,')
          LATEST_TAG=$(echo "$VERSION" | grep -qe '^[0-9]\+\.[0-9]\+\.[0-9]\+$' && \
            echo "latest" || \
            echo "beta")
          docker tag rickbassham/tesla-dashboard:$VERSION rickbassham/tesla-dashboard:$LATEST_TAG
          echo "pushing $VERSION"
          docker push rickbassham/tesla-dashboard:$VERSION
          echo "pushing $LATEST_TAG"
          docker push rickbassham/tesla-dashboard:$LATEST_TAG
